version: '2'
services:
  web:
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - .:/app
    command: bin/rails s -b 0.0.0.0 -p 3000
    environment:
      DATABASE_URL: postgres://postgres:@db
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
volumes:
  bundle:
  node:
