version: '2'
services:
  web: &web
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - .:/app
    command: bin/rails s -b 0.0.0.0 -p 3000
    environment:
      DATABASE_URL: postgres://postgres:@db
      REDIS_URL: redis://redis
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  worker:
    <<: *web
    command: bin/rails environment resque:work
    environment:
      DATABASE_URL: postgres://postgres:@db
      REDIS_URL: redis://redis
      QUEUE: "*"
    ports: []
  db:
    image: postgres
  redis:
    image: redis
volumes:
  bundle:
  node:
